routes/admin.php
<?php

Route::middleware('auth:web-admin')->group(function () {
    Route::get('/', function () {
        return redirect('/admin/dashboard');
    });

    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    });

    Route::post('/logout', 'Admin\Auth\LoginController@logout')->name('logout');

    Route::resource('admins', 'Admin\AdminsController');

    Route::resource('categories', 'Admin\CategoriesController');

    Route::resource('items', 'Admin\ItemsController');

    Route::resource('media', 'Admin\MediaController');
});

Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Admin\Auth\LoginController@login')->name('login');

Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');

Route::get('/password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('/password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('password.update');

routes/front.php
<?php

Route::get('/', function () {
    return view('front.welcome');
});

Auth::routes(['verify' => true]);


Route::middleware('verified', 'auth')->group(function () {
    Route::get('/home', 'Front\HomeController@index')->name('home');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('admin')->name('admin.')->group(function () {
    require __DIR__ . '/admin.php';
});


Route::prefix('vendor')->name('vendor.')->middleware('verified', 'auth', 'isVendorAdmin')->group(function () {
    require __DIR__ . '/vendor.php';
});


if (request()->segment('1') != 'admin') {
    require __DIR__ . '/front.php';
}

resources/views/admin/partials/aside.blade.php
<div class="side-menu" id="left-side-menu">
    <aside class="menu m-t-30 m-l-10">
        <p class="menu-label">General</p>
        <ul class="menu-list">
            <li>
                <a href="{{ url('/admin/dashboard') }}" class="{{ Nav::hasSegment('dashboard', 2) }}">
                    <span class="icon"><font-awesome-icon class="p-t-10" size="xs" icon="tachometer-alt" fixed-width/></span>
                    Dashboard
                </a>
            </li>
            <li>
                <a href="#" class="">
                    <span class="icon" ><font-awesome-icon class="p-t-10" size="xs" icon="chart-bar" fixed-width/></span>
                    Stats
                </a>
            </li>
        </ul>
        <p class="menu-label">Content</p>
        <ul class="menu-list">
            <li>
                <a href="{{ url('/admin/categories') }}" class="{{ Nav::hasSegment('categories', 2) }}">
                    <span class="icon" ><font-awesome-icon class="p-t-10" size="xs" icon="list-ul" fixed-width/></span>
                    Categories
                </a>
            </li>
            <li>
                <a href="{{ url('/admin/media') }}" class="{{ Nav::hasSegment('media', 2) }}">
                    <span class="icon" ><font-awesome-icon class="p-t-10" size="xs" icon="images" fixed-width/></span>
                    Media
                </a>
            </li>
        </ul>
        <p class="menu-label">Administration</p>
        <ul class="menu-list">
            @can('view', 'App\Models\Admin')
                <li>
                    <a href="{{ url('/admin/admins') }}" class="{{ Nav::hasSegment('admins', 2) }}">
                        <span class="icon" ><font-awesome-icon class="p-t-10" size="xs" icon="user-tie" fixed-width/></span>
                        Admins
                    </a>
                </li>
            @endcan
            <li>
                <a class="has-submenu" href="#">
                    <span class="icon" ><font-awesome-icon class="p-t-10" size="xs" icon="users" fixed-width/></span>
                    Vendor Users
                </a>
                <ul class="submenu">
                    <li>
                        <a href="{{ url('/admin/users') }}">
                            Admins
                        </a>
                    </li>
                    <li>
                        <a href="{{ url('/admin/users') }}">
                            Users
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="{{ url('/admin/settings') }}" class="">
                    <span class="icon" ><font-awesome-icon class="p-t-10" size="xs" icon="cogs" fixed-width/></span>
                    Settings
                </a>
            </li>
        </ul>
    </aside>
</div>

resources/views/admin/partials/nav.blade.php
<nav class="navbar has-shadow is-fixed-top" style="transform: translateY(0px);">
    <div class="container">
        <div class="navbar-brand">
            <a href="{{ url('/') }}" class="navbar-item">{{ config('app.name', 'Laravel') }}</a>
            <a class="navbar-item is-hidden-desktop" id="left-slideout-button">
                <span class="icon"><font-awesome-icon class="p-t-10" size="xs" icon="arrow-right" fixed-width/></span>
            </a>
            <div class="navbar-burger burger" data-target="navMenu">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>

        <div class="navbar-menu" id="navMenu">
            <div class="navbar-start"></div>

            <div class="navbar-end">
                @if (auth('web-admin')->guest())
                    <a class="navbar-item " href="{{ route('admin.login') }}">Login</a>
                @else
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link" href="#">{{ auth('web-admin')->user()->name }}</a>

                        <div class="navbar-dropdown">
                            <a class="navbar-item" href="{{ route('admin.logout') }}"
                               onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                Logout
                            </a>

                            <form id="logout-form" action="{{ route('admin.logout') }}" method="POST"
                                  style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
</nav>